# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       nemo-qml-plugin-grilo

# >> macros
# << macros

Summary:    Framework for discovering and browsing media
Version:    0.0.0
Release:    1
Group:      Development/Libraries
License:    BSD
URL:        https://github.com/nemomobile/qtgrilo
Source0:    %{name}-%{version}.tar.bz2
Source100:  nemo-qml-plugin-grilo.yaml
BuildRequires:  pkgconfig(QtCore) >= 4.7.0
BuildRequires:  pkgconfig(QtDeclarative)
BuildRequires:  pkgconfig(grilo-0.2)
Provides:   nemo-qml-plugins-grilo > 0.0.20130114
Obsoletes:   nemo-qml-plugins-grilo <= 0.0.20130114

%description
%{summary}.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake 

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake_install

# >> install post
# << install post


%files
%defattr(-,root,root,-)
%{_libdir}/qt4/imports/org/nemomobile/grilo/libqmlgriloplugin.so
%{_libdir}/qt4/imports/org/nemomobile/grilo/qmldir
# >> files
# << files
