# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       nemo-qml-plugin-grilo-qt5

# >> macros
# << macros

Summary:    Framework for discovering and browsing media
Version:    0.0.0
Release:    1
Group:      Development/Libraries
License:    BSD
URL:        https://github.com/nemomobile/qtgrilo
Source0:    %{name}-%{version}.tar.bz2
Source100:  nemo-qml-plugin-grilo-qt5.yaml
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(grilo-0.2)

%description
%{summary}.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake5

make %{?jobs:-j%jobs}


# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post


%files
%defattr(-,root,root,-)
%{_libdir}/qt5/qml/org/nemomobile/grilo/libqmlgriloplugin.so
%{_libdir}/qt5/qml/org/nemomobile/grilo/qmldir
# >> files
# << files
